# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18ba827cd5da1d8ffe836c5db508fa53c6c396a775ad3ca7c24052cc7f0642dccb2f8eeffb7cd09408c55ffb1e34b4f05ad462fd78a4a613131b1df1cc2374c6

test:
  secret_key_base: 368280d38a42aa5dbbcd9089a7fe0337a9712fc6badcfdce69be11ddec042ee9027c853cc8d46538dc5d424b31f037bf6197033d3e26169a905bfdeec6741bfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
